# Generated by Django 4.2.7 on 2024-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='URL')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_public', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
