# Generated by Django 4.2.7 on 2024-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_newsletter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity_mailing',
            field=models.IntegerField(choices=[(1, 'EVERY_DAY'), (2, 'EVERY_WEEK'), (3, 'EVERY_MONTH')], default=1, verbose_name='Periodicity'),
        ),
    ]
