# Generated by Django 4.2.7 on 2024-02-04 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_newsletter_periodicity_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='status_mailing',
        ),
        migrations.AddField(
            model_name='message',
            name='status_mailing',
            field=models.IntegerField(choices=[(1, 'Создана'), (2, 'В обработке'), (3, 'Завершена'), (4, 'Ошибка')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='lognewsletter',
            name='status_mailing',
            field=models.IntegerField(choices=[(1, 'Создана'), (2, 'В обработке'), (3, 'Завершена'), (4, 'Ошибка')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity_mailing',
            field=models.IntegerField(choices=[(1, 'Каждый день'), (2, 'Каждую неделю'), (3, 'Каждый месяц')], default=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='time_mailing',
            field=models.TimeField(verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
